<?php
/**
 * 04-roles.php
 *
 * - Creates the content_editor role on first load (guarded against duplicate).
 * - Creates the initial content_editor user account from environment variables
 *   (WP_EDITOR_USER / WP_EDITOR_PASSWORD / WP_EDITOR_EMAIL) on first load.
 *
 * The administrator account is created by docker-setup.sh via WP-CLI
 * (wp core install), so this plugin only handles the editor account.
 *
 * Capabilities are scoped to the five custom post types registered in
 * 01-post-types.php. Each type uses a matching capability_type so WordPress
 * generates distinct cap names (edit_ships, publish_ships, etc.).
 */

// All capability names generated by our five custom capability_type values.
// The administrator role must have these explicitly — WordPress does NOT add
// custom capability_type caps to administrator automatically, which means the
// admin menu items stay hidden until they're present in the role's allcaps.
// update_option() (called inside add_cap) is a no-op when the value is
// unchanged, so this is a cheap check on every subsequent page load.
function _zeilshipper_custom_caps(): array {
    $caps = [];
    $types = [
        'ship'        => 'ships',
        'blog_post'   => 'blog_posts',
        'unesco_step' => 'unesco_steps',
        'custom_text' => 'custom_texts',
        'info_board'  => 'info_boards',
        'team_member' => 'team_members',
        'media_item'  => 'media_items',
    ];
    foreach ( $types as $singular => $plural ) {
        $caps = array_merge( $caps, [
            "edit_{$plural}",
            "edit_published_{$plural}",
            "edit_others_{$plural}",
            "edit_private_{$plural}",
            "publish_{$plural}",
            "delete_{$plural}",
            "delete_published_{$plural}",
            "delete_others_{$plural}",
            "delete_private_{$plural}",
            "read_private_{$plural}",
        ] );
    }
    return $caps;
}

add_action( 'init', function () {

    // Guard: WP-CLI fires 'init' while running `wp core install`, before the
    // database tables exist. Skip everything until the schema is in place.
    global $wpdb;
    if ( $wpdb->get_var( "SHOW TABLES LIKE '{$wpdb->users}'" ) !== $wpdb->users ) {
        return;
    }

    // ── Administrator: grant all custom post type caps ───────────────────────
    // Without this, the admin menu items for custom post types are invisible
    // because WordPress checks the plural edit cap (e.g. edit_ships) for menu
    // visibility and administrators don't get custom caps automatically.
    $admin_role = get_role( 'administrator' );
    if ( $admin_role ) {
        foreach ( _zeilshipper_custom_caps() as $cap ) {
            if ( empty( $admin_role->capabilities[ $cap ] ) ) {
                $admin_role->add_cap( $cap );
            }
        }
    }

    // ── content_editor role ──────────────────────────────────────────────────
    if ( ! get_role( 'content_editor' ) ) {
        add_role( 'content_editor', 'Content Editor', [
            // Core
            'read'         => true,
            'upload_files' => true,

            // Ships  (capability_type = 'ship')
            'edit_ships'             => true,
            'edit_published_ships'   => true,
            'publish_ships'          => true,
            'delete_ships'           => true,
            'delete_published_ships' => true,

            // Blog Posts  (capability_type = ['blog_post', 'blog_posts'])
            'edit_blog_posts'             => true,
            'edit_published_blog_posts'   => true,
            'publish_blog_posts'          => true,
            'delete_blog_posts'           => true,
            'delete_published_blog_posts' => true,

            // UNESCO Steps  (capability_type = ['unesco_step', 'unesco_steps'])
            'edit_unesco_steps'             => true,
            'edit_published_unesco_steps'   => true,
            'publish_unesco_steps'          => true,
            'delete_unesco_steps'           => true,
            'delete_published_unesco_steps' => true,

            // Custom Texts  (capability_type = ['custom_text', 'custom_texts'])
            'edit_custom_texts'             => true,
            'edit_published_custom_texts'   => true,
            'publish_custom_texts'          => true,
            'delete_custom_texts'           => true,
            'delete_published_custom_texts' => true,

            // Info Boards  (capability_type = ['info_board', 'info_boards'])
            'edit_info_boards'             => true,
            'edit_published_info_boards'   => true,
            'publish_info_boards'          => true,
            'delete_info_boards'           => true,
            'delete_published_info_boards' => true,

            // Team Members  (capability_type = ['team_member', 'team_members'])
            'edit_team_members'             => true,
            'edit_published_team_members'   => true,
            'publish_team_members'          => true,
            'delete_team_members'           => true,
            'delete_published_team_members' => true,

            // Media Items  (capability_type = ['media_item', 'media_items'])
            'edit_media_items'             => true,
            'edit_published_media_items'   => true,
            'publish_media_items'          => true,
            'delete_media_items'           => true,
            'delete_published_media_items' => true,

            // Explicitly denied (listed for clarity)
            'manage_options'  => false,
            'install_plugins' => false,
            'edit_themes'     => false,
            'switch_themes'   => false,
            'edit_files'      => false,
        ] );
    }

    // ── Initial content_editor account ───────────────────────────────────────
    $editor_login = getenv( 'WP_EDITOR_USER' );
    if ( $editor_login && ! username_exists( $editor_login ) ) {
        $editor_email = getenv( 'WP_EDITOR_EMAIL' ) ?: ( $editor_login . '@localhost' );
        $editor_pass  = getenv( 'WP_EDITOR_PASSWORD' ) ?: wp_generate_password( 20 );

        $user_id = wp_create_user( $editor_login, $editor_pass, $editor_email );

        if ( ! is_wp_error( $user_id ) ) {
            $user = get_user_by( 'ID', $user_id );
            if ( $user ) {
                $user->set_role( 'content_editor' );
            }
        }
    }
}, 1 ); // priority 1 — runs before most plugins hook into 'init'
